### ISSUE TITLE
Add support to release Linux AArch64 wheels 

### ISSUE THREAD

**Issue by odidev** [hibtc/cpymad#101]
I’m trying to build cpymad wheels on Linux AArch64. I’m getting the following error: 
https://github.com/odidev/cpymad/runs/3660038895?check_suite_focus=true#step:7:1617  

Also libquadmath does not have aarch64 support. Please see: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=96016  

@coldfix, Could you please have a look and share your feedback on the same?

**Comment by fsoubelet** [comment]
I would also add onto this issue to ask if maybe Apple Silicon, which is an ARM architecture, could be supported?
I don't know how different from a Linux ARM machine it is, but if it is close it would be great to have the option.

@coldfix if you need someone with an Apple Silicon machine for testing and development I am due to get one in the near future and would love to help!

**Comment by coldfix** [comment]
Hi @odidev,

sorry I didn't answer earlier.

I don't have any experience with building for arm, but I tried your branch locally and it seems that `'lquadmath'` can simply be removed from `setup.py` on aarch64, resulting binary seems to work fine. I have updated master to make this the new default.

Feel free to rebase on master and submit a PR. You would also need to add a test run for the aarch64 wheels.

Best, Thomas

**Comment by coldfix** [comment]
@fsoubelet I don't know anything about that, sorry. If you can get it to work I'm open to accepting PRs on the matter.

**Comment by coldfix** [comment]
In the best case it might be as simple as changing `-DCMAKE_OSX_ARCHITECTURE=x86_64` to the desired target architecture in `build/macos/madx.sh`, but I doubt it will be that simple ;)

**Comment by coldfix** [comment]
@fsoubelet I'm too lazy to try this in depth, but you can look to https://github.com/opencv/opencv-python/blob/master/.github/workflows/build_wheels_macos_m1.yml for some hints on how they do it. They use:

```
      runs-on: macOS-M1]
```

and

```
        export MACOSX_DEPLOYMENT_TARGET=11.0
        arch -arm64 python${{ matrix.python-version }} -m pip wheel --wheel-dir=wheelhouse . --verbose
```

maybe it helps.

**Comment by fsoubelet** [comment]
Thanks for the pointers, I will definitely have a look and report back when I have one of these machines in my hand.

In any case, Rosetta will ensure that `x86-64` versions run, but in the long term it would be nice to have native performance.

**Comment by coldfix** [comment]
@odidev I released new cpymad version with some arm64 wheels. They are untested for now. Let me know if you have any problems with them. Best
