### ISSUE TITLE
EMIT module output is displayed with "delay"

### ISSUE THREAD

**Issue by apoyet** [hibtc/cpymad#102]
Hi, 

I am using cpymad from a light source, and therefore I need to compute the emittances. This is done using the EMIT module of MAD-X, that I am now trying to use with cpymad. 

This module should print - in my use case, in a file - the emittance values (an [issue](https://github.com/MethodicalAcceleratorDesign/MAD-X/issues/1032) has been opened on the MAD-X side in order to store those values on a table). However, when calling this module in cpymad (using either the ```made.input``` command or the ```madx.command.emit()``` one), it seems that the printing of the EMIT module output is somehow delayed (see attached screenshot), until a new command is passed (in the case of the screenshot, ```madx.quit()```. 

This is a bit cumbersome. Is there something that I'm missing here or is there an actual issue? 

Thanks a lot. 
![Screenshot 2021-09-27 at 15 30 15](https://user-images.githubusercontent.com/32321729/134918274-ad26eca7-ac86-4b99-9a71-0cce6c59f7e7.png)

**Comment by coldfix** [comment]
Hi,

sorry to keep you waiting for so long.

Sounds like this could be one of the [Known Issues](http://hibtc.github.io/cpymad/known-issues.html): Try setting the environment variable `GFORTRAN_UNBUFFERED_PRECONNECTED` to `y` **before** creating the `Madx` instance.

If this doesn't work, another possibility might be to add a function into cpymad that the output streams are flushed.

Best

**Comment by apoyet** [comment]
Hi, 

Thanks a lot for your reply, and sorry for overlooking the known issues on the documentation. 

Indeed, the suggested solution seems to be working (even on Mac). 

Thanks again for your help, I will close this issue now. 

Best, 

Axel
