### ISSUE TITLE
Pitfalls on compiling libmadx/cpymad on Linux

### ISSUE THREAD

**Issue by rdemaria** [hibtc/cpymad#115]
I would like to document some pitfalls I recently fell into while compiling libmadx/cpymad from sources on Ubuntu 22.04 and miniconda python environment. I'm not sure if I fully understand all issues, so if you have any advice on how to solve the problems.

First attach the full recipe that worked for me
[mybuildcpymad.txt](https://github.com/hibtc/cpymad/files/9722299/mybuildcpymad.txt)
which consists is building libmadx.a using system libraries disabling `lto`, `tree-vectorize`, `X11` besides what already recommended.

Building a shared libmad.so does not work any longer for me due to issues with gc.

Here the details.

- Compile shared libmadx.so within conda gives issues with the garbage collector gc: 
```
cmake     -DMADX_X11=OFF     -DMADX_STATIC=OFF     -DMADX_ONLINE=OFF     -DBUILD_SHARED_LIBS=ON     -DCMAKE_INSTALL_PREFIX=$MADXDIR     -DCMAKE_C_FLAGS="-fvisibility=protected"         -DCMAKE_CXX_FLAGS="-fvisibility=protected"     -DCMAKE_Fortran_FLAGS="-fvisibility=protected"     -DCMAKE_BUILD_TYPE=Release     -DMADX_INSTALL_DOC=OFF     ..

CMakeFiles/gcmt-dll.dir/alloc.c.o: relocation R_X86_64_PC32 against protected symbol `GC_never_stop_func' can not be used when making a shared object
final link failed: bad value collect2: error: ld returned 1 exit status
```
Changing visibility to `hidden` solves the error above, but still fails with another error:
```
[ 99%] Linking Fortran shared library libmadx.so
/usr/bin/ld: cannot find /usr/lib64/libpthread_nonshared.a: No such file or directory
collect2: error: ld returned 1 exit status
make[2]: *** [src/CMakeFiles/madx.dir/build.make:1652: src/libmadx.so.5.08.01] Error 1
make[1]: *** [CMakeFiles/Makefile2:1356: src/CMakeFiles/madx.dir/all] Error 2
make: *** [Makefile:166: all] Error 2
``` 

-  Use static library from github artifacts: gives runtime errors due to
```
/home/rdemaria/local/cpymad/src/cpymad/libmadx.cpython-39-x86_64-linux-gnu.so: undefined symbol: _ZGVbN2v_cos
```
despite compiling with:
```
python setup.py build_ext -lm --no-X11 --blas --lapack --madxdir=$MADXDIR
```
- Compile static libmad.a with conda: not possible because of missing libgfortran.a
- Compile static library with system libraries (gcc 11)
   - using lto results in mismatch between lto version 11 to lto version 9
   - needs no-lto and no-tree-vectorized for the problem `_ZGVbN2v_...`
- Compile with X11 resulted in run time error Xset... missing

**Comment by rdemaria** [comment]
> Is this within conda environment or outside? If within: which compiler toolchain?
conda environment, here few messages
```
.miniconda3/bin/../lib/gcc/x86_64-conda-linux-gnu/12.1.0/../../../../x86_64-conda-linux-gnu/bin/ld: CMakeFiles/gcmt-dll.dir/alloc.c.o: relocation R_X86_64_PC32 against protected symbol `GC_never_stop_func' can not be used when making a shared object
.miniconda3/bin/../lib/gcc/x86_64-conda-linux-gnu/12.1.0/../../../../x86_64-conda-linux-gnu/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
```

> Did you run cmake from an empty build folder within a clean MAD-X clone?

empty build! 

> On which MAD-X commit is this?

  fd0b07c473436b0231a825ac5495508ca4c2748b   

> from which repo/workflow? cpymad doesn't export the static libmadx.a, IIRC.

https://github.com/MethodicalAcceleratorDesign/MAD-X/actions/runs/3149492030 ->  bin-manylinux1_x86_64-make 

> Or, if this is against .a, it sounds like the error in https://github.com/hibtc/cpymad/issues/79, but you're already using -lm... Maybe try passing -lmvec additionally?

yes it was .a, I have not tried with -lmvec

> did you try -DMADX_STATIC=OFF -DBUILD_SHARED_OBJECTS=OFF?

I'm blocked by the gc error on conda, and other errors if I use system libraries (clearly because conda is another chain)

**Comment by coldfix** [comment]
I just now also tried building inside a conda env and got errors like this:

```
/home/thomas/.local/opt/conda/envs/cpymad/compiler_compat/ld: /usr/lib/libc.so.6: unknown type [0x13] section `.relr.dyn'
/home/thomas/.local/opt/conda/envs/cpymad/compiler_compat/ld: skipping incompatible /usr/lib/libc.so.6 when searching for /usr/lib/libc.so.6
/home/thomas/.local/opt/conda/envs/cpymad/compiler_compat/ld: cannot find /usr/lib/libc.so.6
```

Which is I believe due to some incompatibilities between the system libraries + compiler toolchain and the conda environment. It seems that conda environments require python extensions to be compiled with conda's compiler-toolchain, not with the system compiler.

When now building the cpymad c-extension, I got errors due to lapack not being found:

```
/home/thomas/.local/opt/conda/envs/cpymad/bin/../lib/gcc/x86_64-conda-linux-gnu/11.2.0/../../../../x86_64-conda-linux-gnu/bin/ld: cannot find -llapack: No such file or directory
/home/thomas/.local/opt/conda/envs/cpymad/bin/../lib/gcc/x86_64-conda-linux-gnu/11.2.0/../../../../x86_64-conda-linux-gnu/bin/ld: cannot find -lblas: No such file or directory
```

I guess because the conda compiler toolchain doesn't look in the system directories. So, I think the best way to fix this is by building both MAD-X and cpymad with the conda compiler toolchain. This then worked. The full process looks like this for me:


```
conda create -n cpymad python=3.10
conda activate cpymad
conda install {gcc,gxx,gfortran}_linux-64

# Build MAD-X
(
  mkdir MAD-X/build-conda
  cd MAD-X/build-conda
  cmake .. \
    -DBUILD_SHARED_LIBS=OFF \
    -DMADX_STATIC=OFF \
    -DCMAKE_INSTALL_PREFIX=./dist \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_C_FLAGS="-fvisibility=hidden" \
    -DCMAKE_CXX_FLAGS="-fvisibility=hidden" \
    -DCMAKE_Fortran_FLAGS="-fvisibility=hidden" \
    -DMADX_INSTALL_DOC=OFF \
    -DMADX_ONLINE=OFF \
    -DMADX_FORCE_32=OFF \
    -DMADX_X11=OFF
  cmake --build . --target install -j
)

# Build cpymad:
(
  cd cpymad
  pip install cython
  python setup.py build_ext --madxdir ../MAD-X/build-conda/dist
  pip install -e .
)

```

**Comment by rdemaria** [comment]
With your recipe, in my conda environment (full of packages on 3.9) I get the following error:
```
/usr/bin/ld: cannot find /lib64/libpthread.so.0: No such file or directory
/usr/bin/ld: cannot find /usr/lib64/libpthread_nonshared.a: No such file or directory
collect2: error: ld returned 1 exit status
gmake[2]: *** [src/CMakeFiles/madxbin.dir/build.make:105: src/madx-5.08.01] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:1385: src/CMakeFiles/madxbin.dir/all] Error 2
gmake: *** [Makefile:166: all] Error 2

```
but not if I start from a fresh environment !!!

**Comment by coldfix** [comment]
Ok, so is this solved now or do you prefer to investigate what caused the problem in the other environment? In that case it would be good to have a comprehensive list of installed packages (both conda and pip). You could try uninstalling packages until it starts working (or start from the empty environment and successively install packages until it doesn't).
