### ISSUE TITLE
Python 3.11 Wheels

### ISSUE THREAD

**Issue by fsoubelet** [hibtc/cpymad#119]
Hi,

Would it be possible for you to build and publish `cpymad` wheels for `Python 3.11`? Their absence is failing a lot of CI workflows on our side :(

**Comment by coldfix** [comment]
Hey, sure, will do. Will take me a few days to get around to the issue.

**Comment by fsoubelet** [comment]
Thanks :)

**Comment by coldfix** [comment]
Finally got around to it, sorry for the delays. I will release it in 1.11.0 later on.

**Comment by fsoubelet** [comment]
Thanks!
