### ISSUE TITLE
cpymad 0.10.3 Usage does not work

### ISSUE THREAD

**Issue by cpyman** [hibtc/cpymad#12]
Hey, Thomas

I have succeeded installing cpymad 0.10.3 on 64bits Scientific Linux 7.  However, there exists an error when I run the **Usage**. 
It is the code 
```python
madx = Madx(command_log="log.madx")
```
that raises an exception, which is as follows.

Traceback (most recent call last):
  File "/root/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/cpymad/_rpc.py", line 374, in _dispatch
    response = handler(*args)
  File "/root/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/cpymad/_rpc.py", line 465, in _dispatch_function_call
    module = __import__(modname, None, None, '*')
ImportError: /root/Canopy/appdata/canopy-1.5.1.2730.rh5-x86_64/lib/libgfortran.so.3: version `GFORTRAN_1.4' not found (required by /usr/local/lib/libmadx.so.5.02.04)

**Comment by coldfix** [comment]
Did you compile the package under the very same operating system as you were trying to use it on? If no: do that! On linux distribution of binaries is problemtic if they are dynamically linked. Also make sure to use the same python binary to execute the setup.py.

From what I gather on the web, it may also be possible, that your `/root/Canopy/appdata/canopy-1.5.1.2730.rh5-x86_64/lib/libgfortran.so.3` does not symlink to your newest `libgfortran.so`. If so, try to find your newest libgfortran and create a symlink with the path above.

Let me hear if any of that solves your problem.

**Comment by cpyman** [comment]
When I run the Usage on linux terminal, the error is 

"No module named cpymad.madx".

**Comment by coldfix** [comment]
This error means that you didn't install cpymad for the python distribution you use from your terminal.
Please make sure, you do not confuse different python executables and operating system.

You should build, install and import cpymad in exactly the same circumstances (machine, operating system, python binary).

Maybe its best to test cpymad in an isolated environment, so you don't confuse your python binaries by accident. Do that as follows:

```bash
# install virtualenv (if not installed already)
sudo pip install virtualenv

# create an isolated python environment that has access to packages installed for the system
virtualenv --system-site-packages ENV

# activate virtualenv, do this each time before using cpymad:
source ENV/bin/activate

# go to cpymad folder and then build and install:
python setup.py install

# check if it works
python -c 'import cpymad.libmadx'
```

**Comment by cpyman** [comment]
![2015-04-06 19 19 48](https://cloud.githubusercontent.com/assets/8341044/7003726/f54bc61c-dc91-11e4-82de-774eecfbb7fb.png)
Chinese means can't found the file or direction.

**Comment by coldfix** [comment]
I suggest you use some python distribution other than canopy-enthought. I had only bad experience with this and they charge for additional packages which are open source and you can have for free on any other python.

**Comment by cpyman** [comment]
Good suggestion！
