### ISSUE TITLE
call does not work when double slash is present in file path

### ISSUE THREAD

**Issue by giadarol** [hibtc/cpymad#121]
I observe that the 
```python
madx.input('call, file="folder//file.madx";') # note the double slash in the path
```
does not call the file without raising any error.

On the other hand:
```python
madx.input('call, file="folder/file.madx";')
```
works correctly.

Interestingly this behaviour is not observed if I use MAD-X without cpymad.

**Comment by coldfix** [comment]
This might be due to incorrectly treating the `//` as a comment here. This will take some time to check the difference to MAD-X. The MAD-X input processing is a bit convoluted.

**Comment by coldfix** [comment]
Should be fixed in the new release.
