### ISSUE TITLE
python install cpymad failing on macOS 15 Sequoia

### ISSUE THREAD

**Issue by HelmutCERN** [hibtc/cpymad#140]
Earlier this month, I updated both my x86_64 and arm64 platform macs to the current macOS 15 system  (currently 15.1.1)
All working ok, including building madx on both platforms using cmake

One exception:
So far I did not manage to  
python install cpymad
Fails with  'madX/mad_types_f.h' file not found,
also after building the current madx from source.

Maybe workflows/build.yml needs updating ?

I attach the output of running
python setup.py bdist_wheel  
that also tells me that setup.py install is deprecated.

I also propose to update https://hibtc.github.io/cpymad/installation/macos.html
and replace
-DCMAKE_OSX_ARCHITECTURES=x86_64
with
-DCMAKE_OSX_ARCHITECTURES=`uname -m`
which automatically uses the local architecture.

[bdist_wheel.txt](https://github.com/user-attachments/files/17833337/bdist_wheel.txt)

**Comment by coldfix** [comment]
Hi,
is this failing on both platforms?
According to your `bdist_wheel.txt`, you are building on python 3.13, is that correct for both machines?
Wheels for 3.13 are not yet available, but I'm working on it now.

**Comment by HelmutCERN** [comment]
Yes, it failed on both platforms, both using python 3.13. 
Meanwhile I got python install cpymad  working with macOS 15 on both platforms by doing all the building, not just cpymad, also madX in the same miniforge3 conda environment.
I would be happy to provide further information or checks if useful.

**Comment by coldfix** [comment]
As a heads-up: Currently, it currently looks like github actions doesn't even start the MacOS runners. So I might not be able to deliver wheels for this platform, since I also don't have access to one. I hope that will be resolved when I push the release.

**Comment by coldfix** [comment]
> As a heads-up: Currently, it currently looks like github actions doesn't even start the MacOS runners. So I might not be able to deliver wheels for this platform, since I also don't have access to one. I hope that will be resolved when I push the release.

Turned out, the problem was due to GitHub having dropped support for older MacOS runners and I mainly had to migrate the CI config to use a newer MacOS version.

I have now pushed a new release, and hopefully it should run through in the next 1-2 hours.  I'll be back tonight to check. Let me know if you continue to have issues afterwards.

Best, Thomas
