### ISSUE TITLE
Python 3.13 wheels

### ISSUE THREAD

**Issue by fsoubelet** [hibtc/cpymad#141]
Hi,

Would it be possible to publish wheels of `cpymad` for Python 3.13? The pip install at the moment fails many CI workflows for us.

Thanks :)

**Comment by coldfix** [comment]
Hi,
I'm on it. Unfortunately, there seem to be some issues in updating this time. Also, I will have to drop wheels for EOL'd python versions.

**Comment by coldfix** [comment]
Hi,
sorry, this took longer than expected. I had to fix issues on all three platforms. I have now pushed the release and hopefully it should run through in the next two hours. I'll be back tonight to check.
Best, Thomas

**Comment by coldfix** [comment]
Wheels published
