### ISSUE TITLE
Supress cpymad output to stdio

### ISSUE THREAD

**Issue by mabl** [hibtc/cpymad#15]
When doing parameter sweeps, the output of madx pollutes the standard output.
 I have looked and found no way in the documentation to suppress or redirect that output.

**Comment by coldfix** [comment]
Hey,

redirecting the MAD-X output to an arbitrary file handle can be achieved as follows: 

```
from cpymad.madx import Madx
from cpymad import _rpc
import subprocess

def madx_redirect_stdio(stdout=subprocess.STDOUT, stderr=subprocess.STDOUT):
        with open(os.devnull, 'r') as devnull:
            client, process = _rpc.LibMadxClient.spawn_subprocess(
                stdout=stdout,
                stderr=stderr,
                stdin=devnull,
                bufsize=0)         # unbuffered IO
        madx = Madx(libmadx=client.libmadx)

# drop all stdio:
devnull = open(os.devnull, 'w')
madx_redirect_stdio(devnull, devnull)
```

See also the code in [MadGUI](https://github.com/hibtc/madgui/blob/master/madgui/component/session.py#L65).

I admit, this is a bit hacky and the documentation is almost nonexisting. Probably its a common demand and should be made easier or at least documented. I'll try to add something as soon as I get some time (currently busy with something else, sorry).

Hope, this helps.

**Comment by coldfix** [comment]
I guess I will patch the `Madx` constructor so that it accepts and forwards keyword arguments `stdout` and `stderr`. Hope I get it done by the end of this week.

**Comment by coldfix** [comment]
Okay, took me a bit longer to find some time to do this. You can now simply do

```python
m = Madx(stdout=False)

# or

with open('log.txt', 'w') as f:
    m = Madx(stdout=f)
```

I uploaded a new release on PyPI. Let me know if you have any problems.

Best regards,
Thomas

**Comment by mabl** [comment]
Thanks! That works great for me!
