### ISSUE TITLE
madx set_value has a odd output

### ISSUE THREAD

**Issue by cpyman** [hibtc/cpymad#19]
Hi, Thomas

When I run madx.set_value in ipython, an odd output occurs as follows.

```python
In [17]: madx.set_value('R1QS1->K1', '42')

In [18]: madx.evaluate('R1QS1->K1')
Out[18]: 

￼0.0
```
￼

￼

**Comment by coldfix** [comment]
Post full minimal example.

Specify set value argument as number, not as string.

**Comment by coldfix** [comment]
Ah you just took the example from set_value docstring and executed it without even defining a quadrupole element named R1QS1, right? If so, please think before you post.

**Comment by cpyman** [comment]
Hi,
still don't work.
```python
In [46]: madx.set_value('R1QS1->K1', 42)

In [47]: madx.evaluate('R1QS1->K1')
Out[47]: 
0.0
```
￼

**Comment by coldfix** [comment]
Still didn't post a full example.

**Comment by cpyman** [comment]
I have learned madx and python for 3 months, but I don't know a lot of cpymad. So, if I trouble you very much, very sorry for that.
I really want to understand cpymad.

**Comment by cpyman** [comment]
sorry, it is just a simple example from  set_value docstring.

**Comment by coldfix** [comment]
Okay, then please focus more on providing full information, i.e. all the code/files that is needed to reproduce your problem. In this particular case, the example should start with `from cpymad.madx import Madx` and end with `madx.evaluate(...)`. I don't want to ask you back for all the necessary information everytime.

Initially, I thought, you were working on some sequence, which you didn't post. Now I have to assume, you are executing this without a sequence. But this is still just guessing.

This specific example shows how to set the `K1` attribute of a quadrupole named `R1QS1`. If you want to set a constant value, just use an identifier name, e.g.:

```python
madx.set_value('EULER', 2.718)
madx.evaluate('EULER')
```

**Comment by cpyman** [comment]
If replace ``` R1QS1->K1``` with ```R1QS1```, it works. Why?
```python
In [48]: madx.set_value('R1QS1', 42)

In [49]: madx.evaluate('R1QS1')
Out[49]: 

42.0
```

**Comment by coldfix** [comment]
From now on, please follow the guidelines here https://github.com/hibtc/cpymad#reporting-issues and you will be fine. Otherwise I will limit my responses to you to only one in a few days, so make sure that your questions can be fully understood without asking back.
