### ISSUE TITLE
Cannot initialize Madx class instance

### ISSUE THREAD

**Issue by GitH00t** [hibtc/cpymad#31]
Hey,

I have a problem with initializing the cpymad.madx.Madx() class.
cpymad 0.12.0 for python 3.4.3 installed via pip 
Using conda package manager, all my packages are up to date.
I am just going to post the code I execute + the error message. Maybe you have seen this before.

In [1]: import cpymad.madx as mdx
In [2]: m = madx.Madx()
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-2-fec82ad95609> in <module>()
----> 1 m = madx.Madx()

NameError: name 'madx' is not defined

In [3]: m = mdx.Madx()
Traceback (most recent call last):
  File "C:\Anaconda3\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Anaconda3\lib\site-packages\cpymad\_rpc.py", line 115, in <module>
    LibMadxService.stdio_main(sys.argv[1:])
  File "C:\Anaconda3\lib\site-packages\cpymad\rpc_util\service.py", line 37, in stdio_main
    svc.configure_logging()
  File "C:\Anaconda3\lib\site-packages\cpymad\rpc_util\service.py", line 44, in configure_logging
    logging.basicConfig(logLevel=logging.INFO)
  File "C:\Anaconda3\lib\logging\__init__.py", line 1760, in basicConfig
    raise ValueError('Unrecognised argument(s): %s' % keys)
ValueError: Unrecognised argument(s): logLevel
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
C:\Anaconda3\lib\site-packages\cpymad\rpc_util\client.py in _request(self, kind, *args)
     79         try:
---> 80             self._conn.send((kind, args))
     81         except ValueError:

C:\Anaconda3\lib\site-packages\cpymad\rpc_util\connection.py in send(self, data)
     52         # improves performance by a factor ~50-100 in my tests:
---> 53         return pickle.dump(data, self._send, -1)
     54

OSError: [Errno 22] Invalid argument

During handling of the above exception, another exception occurred:

RemoteProcessCrashed                      Traceback (most recent call last)
<ipython-input-3-272477a4870d> in <module>()
----> 1 m = mdx.Madx()

C:\Anaconda3\lib\site-packages\cpymad\madx.py in __init__(self, libmadx, command_log, error_log, **Popen_args)
    222                 _rpc.LibMadxClient.spawn_subprocess(**Popen_args)
    223             libmadx = self._service.libmadx
--> 224         if not libmadx.is_started():
    225             libmadx.start()
    226         # init instance variables:

C:\Anaconda3\lib\site-packages\cpymad\_rpc.py in DeferredMethod(*args, **kwargs)
     91         def DeferredMethod(*args, **kwargs):
     92             return self.__client._request('function_call', self.__module,
---> 93                                           funcname, args, kwargs)
     94         return DeferredMethod
     95

C:\Anaconda3\lib\site-packages\cpymad\rpc_util\client.py in _request(self, kind, *args)
     84             raise
     85         except IOError:
---> 86             raise RemoteProcessCrashed()
     87         try:
     88             response = self._conn.recv()

RemoteProcessCrashed:

When doing the same in a virtual python 2.7 environment everything works fine. Unfortunately all my tools are written in py3.4, so running cpymad in this virtual environment is not an option for me.
Maybe this issue is related to: 
http://bugs.python.org/issue23207 ?

I tried the same on a different machine and got the same behaviour. Oddly enough, cpymad was working just fine for me a couple of weeks ago and it made my life a lot easier! 
I really like your project!

Cheers!

**Comment by GitH00t** [comment]
Alright, it actually seems  to be related to http://bugs.python.org/issue23207 

I just changed the kwarg you give in \cpymad\rpc_util\service.py in line 44 from LogLevel to level and now it works just fine.
Still keeping the issue open since this will hit other users as well, I suppose.

Cheers!

**Comment by coldfix** [comment]
Hey,

I will fix this ASAP and upload a new version.

Strange that I even used `logLevel` in the first place.. I don't see it documented as the name of the argument in any python version.

I just noticed another small bug with python3.5, which I will fix in the same sub-release.

Best regards and thanks!,
Thomas

**Comment by coldfix** [comment]
(oh and by the way, please use [fences](https://help.github.com/articles/github-flavored-markdown/#fenced-code-blocks) when posting logs, so the formatting doesn't get all messed up and it will be easier to read)

**Comment by GitH00t** [comment]
Yea, I am sorry. I was not really familiar with the whole github formatting and, I admit it, too lazy to figure it out...
Coffee not powerful enough -.- 
I will be better me. I promise!

**Comment by coldfix** [comment]
Great. I uploaded the bug fix to PyPI. Thanks for bringing this to my attention:) Let me know if you have any further problems.
