### ISSUE TITLE
Magnet errors can't be assigned--new

### ISSUE THREAD

**Issue by cpyman** [hibtc/cpymad#36]
Hi, Thomas
When I add some errors to dipoles, cpymad can't calculate the right "x" values,(i.e. the x = 0 always everywhere),  while in the madx it works well.
cpymad code:
```python
import matplotlib.pylab as plt
from cpymad.madx import Madx
madx = Madx(command_log="HIMM_log.madx")
madx.command.call(file="HIMM_cpymad")
twiss0 = madx.twiss(sequence='himm')
plt.plot(twiss0['s'], twiss0['x'], label='x')
```
HIMM_cpymad:
```
//--------------error definition of dipole-------------
SELECT, FLAG = ERROR, CLEAR;
SELECT, FLAG=ERROR, CLASS=B11;
EFCOMP, ORDER=0, RADIUS=0.1,
DKN = {1E-3,0,0},
DKS = {0,0,0};
//--------------plot twiss-------------
SELECT,FLAG=TWISS,COLUMN=name,s,x,y,mux,betx,muy,bety,dx,dy;
TWISS, SAVE, FILE="HIMM-TWISS-BEF";
plot,  range=#s/#e, haxis=s,vaxis=x,y,colour=100; 
```
himm sequence listed in the previous issue.

**Comment by coldfix** [comment]
A separate post in the same issue would have done..

one issue = one topic
one post == one piece of information / update within a topic

There is a bug in cpymad which causes the sequence to be re-USE-d when calling `madx.twiss()`. I will release a new version along with the patch in the next week or so.

In the meantime, you can solve your problem by replacing `tw = madx.twiss(...)` with:

```
madx.command.twiss(...)
tw = madx.get_table('twiss')
```
