### ISSUE TITLE
How to change the magnetic value (i.e. angle for dipole) in a sequence?

### ISSUE THREAD

**Issue by cpyman** [hibtc/cpymad#37]
Hi, Thomas

How to change the value of a magnet in a sequence in cpymad?
I want to change the value (i.e. angle) of some corrector, and to read the closed orbit of each BPM locations.

**Comment by coldfix** [comment]
If you read the [source](https://github.com/hibtc/cpymad/blob/71f1ff319e4a68c8e55e64696136394f6717d37a/cpymad/madx.py#L296) or [documentation](http://hibtc.github.io/cpymad/cpymad/madx.html#cpymad.madx.Madx.set_value) or if you had basic knowledge of MAD-X itself (in cpymad you can do anything you can do in MAD-X using `.input()` as I have stated several times...), you could figure out a way on your own in 5 minutes.

For reference, here are the most relevant ways to achieve this. Assume, you have MAD-X elements, defined like this:

```
k1_qp1 = 1;
qp1: quadrupole, l=1, k1:=k1_qp1;
qp2: quadrupole, l=1, k1=1;
mul: multipole, knl={1, 1, 1};  ! a list
```

in MAD-X, you can change their values as follows:

```
K1_QP1 = 2;
qp2->k1 = 2;            ! also works for qp1
mul, knl={2, 2, 2};     ! this is the only method that works for lists
                        ! (but it also works for qp1,qp2 as well!)
```

where the syntax at the bottom is the most generic, i.e. can be used to modify the values for all cases, and the syntax in the middle can be used to modify either of the first two elements.

Now in cpymad, you have several options:

- you can use `.input()` to directly execute commands that would work in MAD-X itself, so if you know the MAD-X command, you can do in cpymad, e.g.:

```python
m.input('k1_qp1 = 2;')
m.input('qp2->k1 = 2;')
m.input('mul, knl={2, 2, 2}')
```

- there is a convenience method that covers the first two cases:

```python
m.set_value('k1_qp1', 2)
m.set_value('qp2->k1', 2)
```

- the global parameters are also accessible via the `Madx.globals` attribute, so the first case could be written as:

```python
m.globals['k1_qp1']
```

- Also note that I have been planning for some time to create special support for this to cover all three cases in a more uniform and convenient manner, but this remains not implemented as of now, see #25, but I guess you did not even read through the other issues before dropping a new one.
