### ISSUE TITLE
Calculating twiss after adding error to magnets

### ISSUE THREAD

**Issue by mina-acc** [hibtc/cpymad#40]
Hi.
I have already added alignment and field errors to the magnets and then calculate the twiss parameters, same as we do in madx. The problem is that twiss does not see the errors and 'x' and 'y' columns in twiss table are both zero, even after adding errors. Which command shall I use/change to see the impact of errors on the electron trajectory? 
The cpymad code is written below.

p.s. I used while loop to have different seeds, in order to have a better understanding of the effects of errors on electron trajectory.

```
from cern import cpymad
from matplotlib import pyplot as plt
m = cpymad.start_madx()
m.call('btserror.txt')
m.command.beam(sequence='bts', particle='ELECTRON',energy=3)
m.twiss('bts',fname='twissfile.txt', betx=9.054, alfx=-2.5995, bety=11.301, alfy=1.7948, dx=0.2301, dpx=0.0698)

n=0;
while (n<5):
    m.command.eoption(seed='integer')
      # Assign alignment errors to quadrupoles
    m.command.select(flag="error", clear=True)
    m.command.select(flag="error", pattern="qt1")
    m.input('ealign, dx:=tgauss(2)*1e-4,dy:=tgauss(2)*1e-4,dpsi:=tgauss(2)*1e-4;')
    m.command.esave(file="efield.tab0")
      # Assign RELATIVE field errors to quadrupole
    m.command.select(flag="error", clear=True)
    m.command.select(flag="error", pattern="qt1")
    m.input('efcomp, order:=0, radius:=0.013,dknr={tgauss(2)*1e-4,tgauss(2)*1e-3};')
    m.command.esave(file="efield.tab2")
   
    table=m.twiss('bts',fname='twissnew.txt', betx=9.054, alfx=-2.5995, bety=11.301, alfy=1.7948, dx=0.2301, dpx=0.0698)
    column = table.columns
    print column
    f=open('data.txt','a')
    for item1,item2,item3,item4,item5 in zip(column['s'],column['x'],column['y'],column['betx'],column['bety']):
       print>> f,'', item1, '',item2, '', item3, '', item4, '',item5
    f.close()
    n=n+1;
else:
    plt.plot(column['s'], column['x'])
    plt.show()
```

**Comment by coldfix** [comment]
Hey,

I believe this may be an issue due to the implementation of `m.twiss()` calling `select(clear)` under the hood. This is the way it was designed when I initially forked the project, and I'm not sure it's a good thing to do. The solution would be to use instead

```
m.command.twiss(...)
table = m.get_table('twiss')
```

Does this help in your case?

**Comment by mina-acc** [comment]
Unfortunately, no!
Here is the code:

```
m.command.twiss('bts',fname='twissnew.txt', betx=9.054, alfx=-2.5995, bety=11.301, alfy=1.7948, dx=0.2301, dpx=0.0698)

```

and in response, This error comes up:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "build/bdist.linux-x86_64/egg/cern/cpymad/madx.py", line 113, in __call__
  File "build/bdist.linux-x86_64/egg/cern/cpymad/madx.py", line 167, in input
  File "build/bdist.linux-x86_64/egg/cern/cpymad/_libmadx_rpc.py", line 404, in DeferredMethod
  File "build/bdist.linux-x86_64/egg/cern/cpymad/_libmadx_rpc.py", line 246, in _request
  File "build/bdist.linux-x86_64/egg/cern/cpymad/_libmadx_rpc.py", line 171, in send
IOError: [Errno 32] Broken pipe
```

**Comment by coldfix** [comment]
Hey, somehow your answer was deleted.. (?)

I looked at your code, it seems you're using an old version, unmaintained of cpymad!

I recommend, you use the current version, available in this repo, and also on PyPI:

```
pip install cpymad
```

With new cpymad, you will have to do some minor replacements:

```python
# OLD SYNTAX:
from cern import cpymad
m = cpymad.start_madx()
m.twiss('bts', fname='twissfile.txt', ...)
```

becomes

```python
from cpymad import Madx
m = Madx(command_log="commands.madx")
m.twiss('bts', file='twissfile.txt')
```

This example also incorporates the possibility to forward all executed MAD-X commands to a text file. I recommend doing this in case of trouble, so you can check if the generated MAD-X file can be executed without cpymad and whether incorrect commands have been generated.

Best,
Thomas

**Comment by mina-acc** [comment]
Hi,
 I deleted the post to check the code again and be sure that the output is the same as I reported before. Thanks for your quick response in advance! :)
 It seems to work! The MAD-X commands text file was the best source to find the bugs in my code.
 Thanks for being so helpful.

Regards,
Mina

**Comment by coldfix** [comment]
Okay, great. I'll close then.
