### ISSUE TITLE
Docker container

### ISSUE THREAD

**Issue by sterbini** [hibtc/cpymad#44]
Do you know if there is a docker container with cpymad? Thanks!

**Comment by coldfix** [comment]
Hi, not that I'm aware of, but it should be easy to create your own according to your needs.

**Comment by coldfix** [comment]
e.g.:

```Dockerfile
FROM python:3.7-alpine
RUN pip install cpymad
```

**Comment by sterbini** [comment]
Thanks. In case you are interested I prepare a docker image at 

https://hub.docker.com/r/sterbini/juas19/

You can run it, once you have installed Docker Desktop, by:
docker run -p 8888:8888 -v "$PWD":/juas sterbini/juas19

I collect some (draft) help/information on 
https://hackmd.web.cern.ch/s/SJkJKlB1V

Thanks again for your support!

**Comment by coldfix** [comment]
Thanks for the info.

BTW: my recommendation for the average user would be to type `pip install --user cpymad`, at most use a virtualenv.

Also, there is no reliable way to use cpymad on win10 with py3.5 or greater, maybe this should be mentioned in your guide.

Best, Thomas
