### ISSUE TITLE
Suggested interface change: 'table' => 'tables', etc.

### ISSUE THREAD

**Issue by chernals** [hibtc/cpymad#51]
It seems that `table` and `sequence` are mappings and could be renamed `tables` and `sequences` to make for a more meaningful interface.

**Comment by coldfix** [comment]
Hi,

sorry for not getting back to you earlier. In principle, you may be right that the plural form might have been a more consistent choice here, but for now I don't think that's enough justification to break backwards compatibility by renaming these members, nor to introduce ambiguity by adding appropriate aliases.

Best, Thomas
