### ISSUE TITLE
pip install on macos fails 

### ISSUE THREAD

**Issue by iagapov** [hibtc/cpymad#53]
pip install --user cpymad

   creating build/temp.macosx-10.7-x86_64-3.6/src/cpymad
    gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/anaconda3/include -arch x86_64 -I/anaconda3/include -arch x86_64 -I/anaconda3/include/python3.6m -c src/cpymad/libmadx.c -o build/temp.macosx-10.7-x86_64-3.6/src/cpymad/libmadx.o -std=gnu99
    src/cpymad/libmadx.c:623:10: fatal error: 'madX/mad_types_f.h' file not found
    #include "madX/mad_types_f.h"
             ^~~~~~~~~~~~~~~~~~~~
    1 error generated.
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
Command "/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/vp/fh_kzrj97tx5y23r_4n684hw0000gn/T/pip-install-xe6bvybo/cpymad/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/vp/fh_kzrj97tx5y23r_4n684hw0000gn/T/pip-record-pg51jxxw/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /private/var/folders/vp/fh_kzrj97tx5y23r_4n684hw0000gn/T/pip-install-xe6bvybo/cpymad/
  

my settings:

ia$ uname -a
Darwin eduroam-1032.desy.de 18.7.0 Darwin Kernel Version 18.7.0: Tue Aug 20 16:57:14 PDT 2019; root:xnu-4903.271.2~2/RELEASE_X86_64 x86_64

(base) vpn-116:madx ia$ gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/c++/4.2.1
Apple LLVM version 10.0.1 (clang-1001.0.46.4)
Target: x86_64-apple-darwin18.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Comment by coldfix** [comment]
Please check the installation instructions on: https://hibtc.github.io/cpymad/installation/

There are currently no released binaries for Mac, so you will have to compile MAD-X on your own. Refer to the linux section to see how it should work. I have no access to a Mac, so can't help you with mac specific issues. If you find some differences to the linux version, it would be great, if you could write a corresponding documentation section.

Best, Thomas
