### ISSUE TITLE
Accessing Twiss table via element name does not work

### ISSUE THREAD

**Issue by roman-martin** [hibtc/cpymad#55]
I want to retrieve the beta functions at a certain element. To do this I calculate a twiss table and want to access a specific row like ```twisstable["elementname"].betx```. According to the code in [`Table.__getitem__`](https://github.com/hibtc/cpymad/blob/8e2ef6f4b17c38532939d8b15aaeb067204c5fdc/src/cpymad/madx.py#L1063) this should work. However, it doesn't, as the following example shows.
```
# standard stuff: make sequence, define beam, call twiss
from cpymad.madx import Madx
madx = Madx()

madx.input('''
    MQ1: Quadrupole, K1:=0.02, L=1.0;
    MQ2: Quadrupole, K1:=-0.02, L=1.0;

    testseq: SEQUENCE, l = 20.0;
        MQ1, at = 5;
        MQ2, at=18;
    ENDSEQUENCE;
''')
madx.command.beam(particle='proton', energy=7000)
madx.use(sequence='testseq')
twiss = madx.twiss(sequence='testseq', betx=1, bety=1)


# problematic part: try to access element by name string
name_of_third_elem = twiss[2].name # this way we know the name is there
twiss[2].betx #this works fine, as expected
twiss[name_of_third_elem].betx # this does not work, although we just pulled the name string from the twiss table
```

Running the above example results in the following error:
```
KeyError                         Traceback (most recent call last)
~/anaconda3/envs/py3/lib/python3.7/site-packages/cpymad/madx.py in __getitem__(self, column)
   1062         try:
-> 1063             return self._cache[column.lower()]
   1064         except KeyError:

KeyError: 'mq1:1'

During handling of the above exception, another exception occurred:

KeyError                         Traceback (most recent call last)
<ipython-input-7-02b92e3e7aed> in <module>
     18 
     19 twiss[2].betx
---> 20 twiss[name_of_third_elem].betx

~/anaconda3/envs/py3/lib/python3.7/site-packages/cpymad/madx.py in __getitem__(self, column)
   1063             return self._cache[column.lower()]
   1064         except KeyError:
-> 1065             return self.reload(column)
   1066 
   1067     def _query(self, column):

~/anaconda3/envs/py3/lib/python3.7/site-packages/cpymad/madx.py in reload(self, column)
   1117     def reload(self, column):
   1118         """Reload (recache) one column from MAD-X."""
-> 1119         self._cache[column.lower()] = data = self._query(column)
   1120         return data
   1121 

~/anaconda3/envs/py3/lib/python3.7/site-packages/cpymad/madx.py in _query(self, column)
   1071         except ValueError:
   1072             pass
-> 1073         raise KeyError("Unknown table column: {!r}".format(column))
   1074 
   1075     def __iter__(self):

KeyError: "Unknown table column: 'mq1:1'"
```

Note that I pulled the name string from the twiss table itself in the example, so the element should definitely be there.

**Comment by coldfix** [comment]
> According to the code in [`Table.__getitem__`](https://github.com/hibtc/cpymad/blob/8e2ef6f4b17c38532939d8b15aaeb067204c5fdc/src/cpymad/madx.py#L1063) this should work. 

Actually, no. According to the code `__getitem__` treats integers like accessing rows, and strings like accessing columns i.e. `twiss['betx']` is the same as `twiss.betx`.

In order to access only the given row of the twiss table you have to determine the index first, e.g.:

```python
index = madx.sequence.testseq.expanded_elements.index('mq1')
row = twiss[index]
```

However, I'm not sure this approach will be correct if you have any active selections or implicit drifts that are not outputted etc.

**Comment by coldfix** [comment]
You may also try

```python
index = twiss.row_names().index('mq1:1')
```

(with or without the `:1` prefix, I'm not sure)

**Comment by ydutheil** [comment]
In my workflow I generally favor using pandas dataframes

```python
twissdf = twiss.dframe()
print(twissdf.index[2])
print(twissdf.loc['mq1'].betx, twissdf.iloc[2].betx)
```

That may cause lower performance as the data are copied when the dataframe is created.

**Comment by roman-martin** [comment]
Alright, my bad.

Both
`index = twiss.row_names().index('mq1')`
and 
`index = madx.sequence.testseq.expanded_elements.index('mq1')`
worked without the suffix.

I had noticed in my previous attempts that
```
index = numpy.where(twiss.name=='mq1:1')[0][0]
row = twiss[index]
```
resulted in problems because np.int64 =/= int and I figured that there must be an easier way.
