### ISSUE TITLE
dframe extraction of (error)tables not working as expected 

### ISSUE THREAD

**Issue by JoschD** [hibtc/cpymad#57]
Example (sequence from http://bblumi.web.cern.ch/how-tos/ExamplesOfLattices/ExamplesOfLattices/ ):

```python
    # import elements and sequence
    madx = Madx()
    response = requests.get('http://project-ps-optics.web.cern.ch/project-PS-optics/cps/Psb/2015/psb.ele')
    data = response.text
    madx.input(data)

    response = requests.get('http://project-ps-optics.web.cern.ch/project-PS-optics/cps/Psb/2015/psb.seq')
    data = response.text
    madx.input(data)

    # create beam
    madx.beam(particle='PROTON', pc=0.311, exn=15E-6*3.0, eyn=8E-6*3.0, sige=1.35E-3*3.0, sigt=230E-9)

    # get error table of sequence
    madx.use(sequence='psb1')
    madx.etable(table="errors")
    df = madx.table.errors.dframe()
```

Results in error:
```
Traceback (most recent call last):
  File "python3.7/site-packages/cpymad/madx.py", line 1063, in __getitem__
    return self._cache[column.lower()]
KeyError: 'k0l'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/snap/pycharm-community/194/plugins/python-ce/helpers/pydev/pydevd.py", line 1438, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/snap/pycharm-community/194/plugins/python-ce/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "bblumi_example.py", line 124, in <module>
    df = madx.table.errors.dframe()
  File "python3.7/site-packages/cpymad/madx.py", line 1142, in dframe
    return pd.DataFrame(self.copy(columns), index=self.row_names())
  File "python3.7/site-packages/cpymad/madx.py", line 1137, in copy
    return {column: self[column] for column in columns}
  File "python3.7/site-packages/cpymad/madx.py", line 1137, in <dictcomp>
    return {column: self[column] for column in columns}
  File "python3.7/site-packages/cpymad/madx.py", line 1065, in __getitem__
    return self.reload(column)
  File "python3.7/site-packages/cpymad/madx.py", line 1119, in reload
    self._cache[column.lower()] = data = self._query(column)
  File "python3.7/site-packages/cpymad/madx.py", line 1073, in _query
    raise KeyError("Unknown table column: {!r}".format(column))
KeyError: "Unknown table column: 'k0l'"
```
(reduced the file paths a bit)

Running on :
Ubuntu 20.04
Python 3.7.7
cpymad 1.4.1
MADX 5.05.01

Am I missing something?

**Comment by JoschD** [comment]
Workaround:
call 
```
madx.select(flag="error")
madx.etable(table="errors")
```
 


Also: if there would be another `clear` in between, it would fail again. 
```
madx.select(flag="error")
madx.select(flag="error", clear=True)
madx.etable(table="errors")
```

**Comment by rdemaria** [comment]
Error table is destroyed every time by `use` and needs to be created somehow. I don't see any error assignment in the input. What are you trying to do?

**Comment by JoschD** [comment]
Something totally different, but that was the shortest example I could come up with that replicates the error. As far as I can see, it should not be crashing that way. 
The error-table should be filled with zeros. 
But there is something weird going on in the `copy()` function that get's the columns from the table but when it asks for the content, the table says the columns are not there.

**Comment by coldfix** [comment]
Hi,

> As far as I can see, it should not be crashing that way.
The error-table should be filled with zeros.
But there is something weird going on in the copy() function that gets the columns from the table but when it asks for the content, the table says the columns are not there.

Yes, I think it's fair to say that the current behaviour may be confusing. I believe this is most likely due the `table.columns` field containing column names for which there is no data (in which case `table_get_column` in MAD-X source code will return a `V` type code and hence our `get_table_column` routine will abort). I've got a likely fix in #58 which should return an empty dataframe (without columns) instead of excepting in this case (but no zeros either).

However, it might be a while until we get this merged and released, the reason for the holdup is explained in #56.

**Comment by JoschD** [comment]
This still seems to be the case, btw. (version 1.8.1)

Example:
```
from cpymad.madx import Madx

madx = Madx()
madx.input("""
beam;

mqf.k1 =  0.3037241107;
mqd.k1 = -0.3037241107;

fodo: sequence, l=10, refer=entry;
mqf: quadrupole, at=0, l=1, k1:=mqf.k1;
dff: drift,      at=1, l=4;
mqd: quadrupole, at=5, l=1, k1:=mqd.k1;
dfd: drift,      at=6, l=4;
endsequence;

use, sequence=fodo;
twiss, sequence=fodo, x=0.1;
""")


madx.select(flag='error', clear=True)
madx.etable(table='error')
df = madx.table.error.dframe()
```

**Comment by coldfix** [comment]
Thanks, I'll have a look.

**Comment by coldfix** [comment]
Okay, I've identified the issue and added a test this time. Hope this will solve the problem.
