### ISSUE TITLE
Building on windows is hard

### ISSUE THREAD

**Issue by coldfix** [hibtc/cpymad#6]
Building and deploying on windows systems is still not easy, since there is often no compiler available and, currently, only gcc is supported by `setup.py`. Switching from a cython to a [ctypes](https://docs.python.org/3.3/library/ctypes.html) binding could remedy this issue. Another possibility might be [CFFI](https://cffi.readthedocs.org/en/).

Implications of using a ctypes binding:
- tedious python code
- might need to write a separate MAD-X extension to expose a more convenient C API (or integrate into MAD-X upstream, but they are unlikely to accept the contribution)
- might be possible without improved C API, with even more tedious python code 
- no more static binding
- decreased performance (not significantly, I guess)

**Comment by carlkl** [comment]
You might consider using the mingwstatic builds as gcc compilers toolchains. These mingw-w64 based builds has been assembled and patched to simplify the creation of gcc based python extensions on Windows. 

See https://bitbucket.org/carlkl/mingw-w64-for-python/downloads for download and https://bitbucket.org/carlkl/mingw-w64-for-python/downloads/mingwstatic-2014-11-readme.md for some explanations. 

The latest winpython builds https://winpython.github.io integrates mingwstatic as default for both 32 and 64 bit.

**Comment by coldfix** [comment]
@carlkl thanks for your hint. I will look into your repositories and see if it will be useful. :)

**Comment by carlkl** [comment]
@coldfix, after some manual tweaking of the build process I got: 
https://bitbucket.org/carlkl/mingw-w64-for-python/downloads/cpymad-0.10.1-cp27-none-win_amd64.whl
That is cpymad for python2.7 amd64 (64bit).

**Comment by coldfix** [comment]
Hey @carlkl. If I may ask, are you interested in seeing 64bit binaries of this package on PyPI (have 32bit already) - or did you just stumble across this package by accident and decided to inform me about a convenient build platform?

I didn't really think this package is used by anyone else outside HIT at the moment, but if that turns out to be wrong, I might be more careful when breaking API, etc;)

**Comment by carlkl** [comment]
This package may be of interest for others in the accelerator community. BTW: I stupmbled upon it due to the HIT IPAC14 paper. The mentioned mingw-w64 builds assure correct MS CRT runtime useage and self contained pyd's without the need to deploy further gcc runtimes. These runtime DLLs are missing in your 32 bit distro.

**Comment by coldfix** [comment]
Sounds great! I just tried to build cpymad/madx (for 32bit), but I ran into problems while linking MAD-X:

```
ld.exe: cannot find -lgcc_eh
```

Before I research how to solve this, maybe you had the same problem and can tell me?

**Comment by carlkl** [comment]
@coldfix coldfix, just remove ```-lgcc_eh```  from the command line given in 
```
build/src/CMakeFiles/madxbin.dir/link.txt
```

**Comment by coldfix** [comment]
Closing this for now, distributing WinPython builds seems good enough.
