### ISSUE TITLE
Twiss dframe segfaults on macOS when interpolating elements

### ISSUE THREAD

**Issue by fsoubelet** [hibtc/cpymad#72]
Hi @coldfix,

I have encountered a strange bug recently. I can guarantee that it is a result of  `cpymad` and not `MAD-X`.

**Platform**: `macOS 10.15.7`
**MAD-X version**: `5.06.01`
**cpymad version**: `1.6.2`

I'm getting a `segmentation fault` during  an `UnpicklingError`when trying to access `table.twiss.dframe()`.
It appears the issue is only present when I use the `interpolate` command in my madx script.
Here is a reproducible scenario, saved as `test.madx`:

```
! PARAMETERS
circumference = 1000.0;
ncell = 24;
lcell = circumference/ncell;
lq = 3.00;
angleBending = 2.0*pi/(4*ncell);

! STRENGTHS
kqf = 0.0228 * lq;
kqd = -0.0228 * lq;
lsex = 0.00001;
ksf = 0;
ksd = 0;

! ELEMENTS
mb: multipole, knl:={angleBending};
qf: multipole, knl:={0, kqf};
qd: multipole, knl:={0, kqd};
msf: multipole, knl:={0, 0, ksf};
msd: multipole, knl:={0, 0, ksd};

! DECLARE SEQUENCE
EXAMPLE: sequence, refer=centre, l=circumference;
   start_machine: marker, at = 0;
   n = 1;
   while (n < ncell+1) {
    qf: qf,   at=(n-1)*lcell;
    msf: msf, at=(n-1)*lcell + lsex/2.0;
    mb: mb,   at=(n-1)*lcell + 0.15*lcell;
    mb: mb,   at=(n-1)*lcell + 0.35*lcell;
    qd: qd,   at=(n-1)*lcell + 0.50*lcell;
    msd: msd, at=(n-1)*lcell + 0.50*lcell + lsex/2.0;
    mb: mb,   at=(n-1)*lcell + 0.65*lcell;
    mb: mb,   at=(n-1)*lcell + 0.85*lcell;
    at=(n-1)*lcell;
    n = n + 1;
}
end_machine: marker at=circumference;
endsequence;

! MAKE BEAM & ACTIVATE SEQUENCE
beam, particle=proton, sequence=EXAMPLE, energy=20.0;
use, sequence=EXAMPLE;

! INTERPOLATE
select, flag=interpolate, class=drift, slice=5, range=#s/#e;

! TWISS
select, flag=twiss, clear;
twiss, file="output.tfs";
```

I am getting the error with a simple `crash.py` file:
```python
from cpymad.madx import Madx

mad = Madx()
mad.call("test.madx")
print(mad.table.twiss.dframe())
```

Running simply  `madx test.madx` does not lead to any problem or error.
When running `python crash.py`, the error is the following:
```
Traceback (most recent call last):
  File "/Users/felixsoubelet/anaconda3/lib/python3.8/site-packages/cpymad/madx.py", line 1063, in __getitem__
    return self._cache[column.lower()]
KeyError: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "crash.py", line 7, in <module>
    print(mad.table.twiss.dframe())
  File "/Users/myusername/anaconda3/lib/python3.8/site-packages/cpymad/madx.py", line 1142, in dframe
    return pd.DataFrame(self.copy(columns), index=self.row_names())
  File "/Users/myusername/anaconda3/lib/python3.8/site-packages/cpymad/madx.py", line 1137, in copy
    return {column: self[column] for column in columns}
  File "/Users/myusername/anaconda3/lib/python3.8/site-packages/cpymad/madx.py", line 1137, in <dictcomp>
    return {column: self[column] for column in columns}
  File "/Users/myusername/anaconda3/lib/python3.8/site-packages/cpymad/madx.py", line 1065, in __getitem__
    return self.reload(column)
  File "/Users/myusername/anaconda3/lib/python3.8/site-packages/cpymad/madx.py", line 1119, in reload
    self._cache[column.lower()] = data = self._query(column)
  File "/Users/myusername/anaconda3/lib/python3.8/site-packages/cpymad/madx.py", line 1070, in _query
    return self._libmadx.get_table_column(self._name, column.lower())
  File "/Users/myusername/anaconda3/lib/python3.8/site-packages/minrpc/client.py", line 159, in DeferredMethod
    return self.__client._request('function_call', self.__module,
  File "/Users/myusername/anaconda3/lib/python3.8/site-packages/minrpc/client.py", line 107, in _request
    response = self._communicate((kind, args))
  File "/Users/myusername/anaconda3/lib/python3.8/site-packages/minrpc/client.py", line 117, in _communicate
    return self._conn.recv()
  File "/Users/myusername/anaconda3/lib/python3.8/site-packages/minrpc/connection.py", line 47, in recv
    return pickle.load(self._recv)
_pickle.UnpicklingError: pickle data was truncated
[1]    47362 segmentation fault  python crash.py
```

Now, **when commenting out line 48 in `test.madx`, the line with the `interpolate` command, all runs fine** including the python script. This error could not be reproduced in my desktop running `Ubuntu 18.04`.

I don't really have any  more insight on what the cause of the issue is. I know you don't have a `macOS` machine at hand to tinker with, so let me know if you need me to provide some more information or run tests.

**Comment by coldfix** [comment]
Hi,

thanks for the well-written bug report :+1:

I can reproduce the crash on linux.

The error occurs only if using libmadx as subprocess, but not if called in the local process, e.g.:

```python
import cpymad.libmadx as libmadx
mad = Madx(libmadx=libmadx)
mad.call('test.madx')
print(mad.table.twiss.name)
```

Als:, the error disappears when decreasing the size of the sequence (`ncell < 23` or by removing elements).

Together with the error message, this indicates that there may be a transmission error from the RPC mechanism, e.g. due to limited pipe buffer or max message size. I will investigate more later or on the weekend.

**Comment by rdemaria** [comment]
I don't know if it is related and I could not investigate much, but I have also experienced an issue with pickle complaining from truncated data. I did not get segmentation fault though.

**Comment by coldfix** [comment]
I can now confirm that this is due to `pickle.load()` giving truncation errors when the message written by `pickle.dump()` exceeds a certain size (presumably depending on the underlying channel). I have a fix for minrpc that mitigates this by passing the message length explicitly and reading until the full message is received. Will do a release later.

The subsequent segfault might be due to trying to unpickle on remnant data from the previous message (?).

**Comment by coldfix** [comment]
Hi,

I have issued a new `minrpc 0.1.0` release that should hopefully fix this issue (does on linux). You can upgrade as follows:

```
pip install -U minrpc
```

and then try again.

**Comment by fsoubelet** [comment]
I can confirm that upgrading the `minrpc` version fixes the issue on my `macOS` machine. Thanks for the (super) quick fix!

**Comment by coldfix** [comment]
Awesome, and thanks for the bug report!

In hindsight, I'm astonished that I never ran into this problem myself, as this crashes any program that requests or sends data `> ~65KB` in one go.
