### ISSUE TITLE
Missing log and while loop

### ISSUE THREAD

**Issue by sterbini** [hibtc/cpymad#75]
Hi,

if I do 
```python
from cpymad.madx import Madx
mad = Madx(command_log="my_log.log")
mad.input('''
i=0;
while (i < 5) {
value, i;
i=i+1;
}
''')
```
 *my_log.log* is empty.

If I use the ";" that is 
```python
from cpymad.madx import Madx
mad = Madx(command_log="my_log.log")
mad.input('''
i=0;
while (i < 5) {
value, i;
i=i+1;
};
''')
```
or if I do

```python
from cpymad.madx import Madx
mad = Madx(command_log="my_log.log")
mad.input('''
i=0;
while (i < 5) {
value, i;
i=i+1;
}
''')
mad.input('i=2;')
```
 *my_log.log*  is written again as expected...
It is a detail (and perhaps connected with the curl braces), but perhaps it is not a wanted (expected) behaviour.

Cheers,

**Comment by coldfix** [comment]
Hi,

I can't reproduce this locally. For me, the log file contains all expected text even for the first example. Which version of cpymad do you have?

In general, I don't recommend using `input()` for complex input. One of the points of cpymad is to be able to replace the MAD-X control structures by python ones, i.e. use `while` loop in python, not in MAD-X. Historically, the `Madx.input()` function could only deal with single-line statements, no loops, if/else, macros, etc. This has been improved in recent versions, but I would still recommend using `Madx.call(filename)` for complex input (we should probably document this).

**Comment by sterbini** [comment]
Hi,

I am using version 1.4.1. 
I tried to reproduce the issue: I did not manage. Sorry for the confusion. I propose to close the issue.
