### ISSUE TITLE
Sporadic failures on "input" or "call" on Windows

### ISSUE THREAD

**Issue by fsoubelet** [hibtc/cpymad#77]
Hi,

As part of a CI/CD pipeline I have Github Actions runnings tests. Recently these have randomly failed on the Windows versions of the Github workers (`windows-latest` in configurations).

These errors occur randomly and for different parts of the code, so I can't point to a specific command that triggers them, but it's happened enough times that I thought I would report it.

**OSes:** `windows-latest` (Windows Server 2019)
**Python versions:** `3.7` and `3.8`
**cpymad versions:** `1.6.3`

The errors I've encountered are either (copy-pasted from the logs):
```
         madx = Madx(stdout=False)
>       madx.call(str(LHC_SEQUENCE.absolute()))
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
.venv\lib\site-packages\cpymad\madx.py:336: in call
    self.command.call(file=file)
.venv\lib\site-packages\cpymad\madx.py:774: in __call__
    return self._madx.input(util.format_command(self, *args, **kwargs))
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <cpymad.madx.Madx object at 0x000001AD4946A6D0>
text = 'call, file="D:\\a\\PyhDToolkit\\PyhDToolkit\\tests\\inputs\\lhc_as-built.seq";'

    def input(self, text):
        """
        Run any textual MAD-X input.
    
        :param str text: command text
        :returns: whether the command has completed without error
        :rtype: bool
        """
        text = text.rstrip(';') + ';'
        if self._enter_count > 0:
            self._batch.append(text)
            return True
        # write to history before performing the input, so if MAD-X
        # crashes, it is easier to see, where it happened:
        if self.history is not None:
            self.history.append(text)
        if self._command_log:
            self._command_log(text)
        try:
            with self.reader:
                return self._libmadx.input(text)
        except _rpc.RemoteProcessCrashed:
            # catch + reraise in order to shorten stack trace (~3-5 levels):
            pass
>       raise RuntimeError("MAD-X has stopped working!")
E       RuntimeError: MAD-X has stopped working!
```

or the following:
```
>       madx = Madx(stdout=False)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
.venv\lib\site-packages\cpymad\madx.py:171: in __init__
    if not libmadx.is_started():
.venv\lib\site-packages\minrpc\client.py:160: in DeferredMethod
    funcname, args, kwargs)
.venv\lib\site-packages\minrpc\client.py:112: in _request
    return self._dispatch(response)
.venv\lib\site-packages\minrpc\client.py:123: in _dispatch
    return handler(*args)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <cpymad._rpc.LibMadxClient object at 0x00000213BE3BB2C8>
exc_type = <class 'ImportError'>
message = 'Traceback (most recent call last):\n  File "D:\\a\\PyhDToolkit\\PyhDToolkit\\.venv\\lib\\site-packages\\minrpc\\servi...name, None, None, \'*\')\nImportError: DLL load failed: The paging file is too small for this operation to complete.\n'

    def _dispatch_exception(self, exc_type, message):
        """Dispatch an exception."""
        # Raise a wrapper exception type to avoid problems if the constructor
        # expects a different arguments than a message string:
        raise type(exc_type.__name__, (exc_type,), {
            '__str__': lambda *args: message,
>           '__init__': lambda *args: None})
E       minrpc.client.ImportError: Traceback (most recent call last):
E         File "D:\a\PyhDToolkit\PyhDToolkit\.venv\lib\site-packages\minrpc\service.py", line 85, in _dispatch
E           response = handler(*args)
E         File "D:\a\PyhDToolkit\PyhDToolkit\.venv\lib\site-packages\minrpc\service.py", line 101, in _dispatch_function_call
E           module = __import__(modname, None, None, '*')
E       ImportError: DLL load failed: The paging file is too small for this operation to complete.
```

**Comment by coldfix** [comment]
Weird.

Is that the "official" cpymad binary or custom built?

The second message seems to imply you're out of memory. How is the memory usage in that part of your script?

What is the error frequency approximately? 1/10, 1/100, 1/1000?

Can you also include a link to the other project's CI (if that is public)?

**Comment by fsoubelet** [comment]
Hi again,

The `cpymad` is the one taken directly from PyPI with `pip install cpymad`.
I am unsure about the memory situation, but this might have to do with how `pytest` fixtures work internally?
Difficult to properly get the frequency too, I would say 1/50 calls maybe.

Here are links to CI runs that show the error:
- https://github.com/fsoubelet/PyhDToolkit/actions/runs/548379230
- https://github.com/fsoubelet/PyhDToolkit/actions/runs/548265572

Those are for the branch at https://github.com/fsoubelet/PyhDToolkit/tree/twiss_utils

**Comment by fsoubelet** [comment]
Quick update: the issues came in preparing and returning `cpymad.madx.Madx` instances in fixtures. It appears that instead yielding the instances and then executing `madx.exit()` helps with the memory usage, and solved the problem.

**Comment by coldfix** [comment]
> Quick update: the issues came in preparing and returning `cpymad.madx.Madx` instances in fixtures. It appears that instead yielding the instances and then executing `madx.exit()` helps with the memory usage, and solved the problem.

Great!  Is it solved then?


Btw Madx instances can also be used as context manager to avoid having to call exit explicitly. In the case of the fixture this might look as follows:

```python
with Madx(...) as madx:
    yield madx
```

**Comment by fsoubelet** [comment]
Considering I haven't had the issue once since the aforementioned change, I would say this is fixed. Thanks for the hints :)

**Comment by coldfix** [comment]
Great. Let us know if the issue occurs again.

Maybe the documentation should include a hint about this.
