### ISSUE TITLE
How are the MADX binaries built that are included in wheels?

### ISSUE THREAD

**Issue by Dominik1123** [hibtc/cpymad#78]
Hello, I have a question regarding the build of MADX binaries that ship with the `cpymad` wheels.
Specifically, I have installed `cpymad` in the following way: `pip install cpymad --only-binary cpymad` (Python 3.9)
However I observed that matching results would differ when run through `cpymad` as opposed to running directly through the MADX binaries obtained from [their website](https://madx.web.cern.ch/madx/releases/last-rel/) (version 5.06.01; tested both `intel` and `gnu` compiled version).
So I figured there must be a difference in the way MADX is compiled ([`setup.py`](https://github.com/hibtc/cpymad/blob/master/setup.py#L48) hints that there are compile options, but it doesn't reveal the choices eventually made)?

**Comment by coldfix** [comment]
Hi,

look in [.github/build](https://github.com/hibtc/cpymad/tree/master/.github/build) in the subfolder corresponding to your platform.

If you observed differences in behaviour, it would be nice if you can document them.

**Comment by Dominik1123** [comment]
I checked the build steps for `cpymad` however I couldn't find information on how the official MADX binaries are built. I see there is [this build report](https://madx.web.cern.ch/madx/releases/last-rel/build-test-lxplus.out) however it doesn't seem to include the actual build commands. Do you know about the MADX build process?
I'm attaching a script for which you can observe the difference in behavior: the resulting penalty function from matching is different and so are the final values of variables.
I tested

* `./madx-linux64-gnu test.madx.txt` vs.
* `python -c 'from cpymad.madx import Madx; Madx().call(file="test.madx.txt")'`.
* [Example MADX script for testing](https://github.com/hibtc/cpymad/files/6048451/test.madx.txt)

**Comment by ydutheil** [comment]
@Dominik1123 have you checked you are comparing the same MADX version ? Using both 5.06.01 I get the same results. 

Also, isn't the information on how the madx binaries are built [here](https://github.com/hibtc/cpymad/blob/master/.github/checkout-madx/action.yml)?

**Comment by Dominik1123** [comment]
@ydutheil That's curious since I also compared 5.06.01 for both. When I use the following test script:

```lang-bash
#!/bin/bash

wget https://madx.web.cern.ch/madx/releases/last-rel/madx-linux64-gnu
# wget https://madx.web.cern.ch/madx/releases/5.06.01/madx-linux64-gnu  # similar results
chmod +x madx-linux64-gnu

echo 'MADX'
echo '----'
./madx-linux64-gnu test.madx | grep -E 'MAD-X|Final Penalty Function'
echo ''

echo 'CPYMAD'
echo '------'
python -c 'from cpymad.madx import Madx; Madx().call(file="test.madx.txt")' | grep -E 'MAD-X|Final Penalty Function'
echo ''
```

I get the following output:

```lang-none
$ ./test.sh 
--2021-02-26 10:39:23--  https://madx.web.cern.ch/madx/releases/last-rel/madx-linux64-gnu
Resolving madx.web.cern.ch (madx.web.cern.ch)... 188.184.21.19, 2001:1458:d00:34::100:129
Connecting to madx.web.cern.ch (madx.web.cern.ch)|188.184.21.19|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 25988320 (25M)
Saving to: ‘madx-linux64-gnu’

madx-linux64-gnu                     100%[=====================================================================>]  24,78M  6,94MB/s    in 3,7s    

2021-02-26 10:39:27 (6,72 MB/s) - ‘madx-linux64-gnu’ saved [25988320/25988320]

MADX
----
  +     MAD-X 5.06.01  (64 bit, Linux)       +
Final Penalty Function =   1.33844617e-13
  +          MAD-X finished normally         +

CPYMAD
------
  +     MAD-X 5.06.01  (64 bit, Linux)       +
Final Penalty Function =   0.00000000e+00

```

Since it works for you, I conclude that it must be my installation of `cpymad` that's somehow broken. I installed it in the following way:

```lang-none
$ conda create -n test-cpymad python=3.9
[...]
$ conda activate test-cpymad
$ python -m pip install cpymad --only-binary cpymad
Collecting cpymad
  Using cached cpymad-1.6.3-cp39-cp39-manylinux1_x86_64.whl (5.1 MB)
Collecting minrpc>=0.0.8
  Using cached minrpc-0.1.0-py2.py3-none-any.whl (12 kB)
Collecting numpy
  Using cached numpy-1.20.1-cp39-cp39-manylinux2010_x86_64.whl (15.4 MB)
Collecting importlib-resources
  Using cached importlib_resources-5.1.0-py3-none-any.whl (24 kB)
Installing collected packages: numpy, minrpc, importlib-resources, cpymad
Successfully installed cpymad-1.6.3 importlib-resources-5.1.0 minrpc-0.1.0 numpy-1.20.1
$ conda list | grep cpymad
# packages in environment at /home/dominik/miniconda3/envs/test-cpymad:
cpymad                    1.6.3                    pypi_0    pypi
```

I also tested this with Python 3.8 and Python 3.7 and the results when running `cpymad` on `test.madx.txt` are similar.

About the build process, I'm not at all familiar with this and it is difficult for me to extract the relevant bits in order to assess whether there is a difference between the MADX and Cpymad way of building the binaries.

In case it's relevant, I'm using `Ubuntu 20.04.2 LTS` and I have the following processors:

```lang-none
$ sudo lshw | grep -i cpu
     *-cpu
          description: CPU
          product: Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz
          bus info: cpu@0
          version: Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz
          capabilities: lm fpu fpu_exception wp vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp x86-64 constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb invpcid_single pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid rdseed adx smap intel_pt xsaveopt dtherm ida arat pln pts md_clear flush_l1d cpufreq
```

**Comment by coldfix** [comment]
> I checked the build steps for `cpymad` however I couldn't find information on how the official MADX binaries are built. I see there is [this build report](https://madx.web.cern.ch/madx/releases/last-rel/build-test-lxplus.out) however it doesn't seem to include the actual build commands. Do you know about the MADX build process?

I'm sorry, no I don't know the build instructions for the official MAD-X binaries, and AFAIK they are neither part of the MAD-X repository itself nor publicly documented. You may have to ask over there.

> I'm attaching a script for which you can observe the difference in behavior: the resulting penalty function from matching is different and so are the final values of variables.
> I tested
> 
>     * `./madx-linux64-gnu test.madx.txt` vs.
> 
>     * `python -c 'from cpymad.madx import Madx; Madx().call(file="test.madx.txt")'`.
> 
>     * [Example MADX script for testing](https://github.com/hibtc/cpymad/files/6048451/test.madx.txt)

Thanks.

> Since it works for you, I conclude that it must be my installation of `cpymad` that's somehow broken. 

Could be that @ydutheil is on a different platform where it happens to work. I'll try out the linux build if it works for me. I can't promise that I'll make it today.

FTR, it is not unexpected to find differences between cpymad and madx due to different build mode. This is partly unavoidable because we have to build as shared library, while madx builds a static binary to avoid runtime dependencies. And this difference alone can have a huge impact. However, whenever specific differences manifest, we should definitely investigate and check if they can be avoided by using different build flags etc.


@ydutheil wrote:

> Also, isn't the information on how the madx binaries are built [here](https://github.com/hibtc/cpymad/blob/master/.github/checkout-madx/action.yml)?

No, that's how the cpymad build process fetches the MAD-X sources, not how the official MAD-X binary is built.

**Comment by coldfix** [comment]
> AFAIK they are neither part of the MAD-X repository itself nor publicly documented.

I could be wrong though. The build report you showed looks like it was generated from the scripts in this [MAD-X/scripts/](https://github.com/MethodicalAcceleratorDesign/MAD-X/blob/master/scripts/).

However, note that MAD-X official binaries are built using the GNU make build scripts, while cpymad is built using cmake (because it was easier to build a shared object with this build system) - so it may not be easy to identify the concrete differences other than going through the build flags on individual files.

**Comment by ydutheil** [comment]
I can reproduce the pure MADX result when using cpymad on my linux machine. However, when running cpymad on the WSL of my windows machine I indeed get different results.

I see similar behaviour with the other methods, except the JACOBIAN one that gives the same result everywhere.

I then tried the random generators **ranf** and **gauss** but I see the same output from both!

**Comment by coldfix** [comment]
> 
> I get the following output:
> 
> ```
> [...]
> 
> MADX
> ----
>   +     MAD-X 5.06.01  (64 bit, Linux)       +
> Final Penalty Function =   1.33844617e-13
>   +          MAD-X finished normally         +
> 
> CPYMAD
> ------
>   +     MAD-X 5.06.01  (64 bit, Linux)       +
> Final Penalty Function =   0.00000000e+00
> ```

I get the same behaviour as you do.

However, the differences is on the order of 1e-13 which looks like it could be explained by numeric noise (different compiler, order of floating point operations, etc), since it's not too far from machine precision. Does this lead to some harmful effect in your analysis or is it negligible, i.e. just a difference that you noticed and were concerned about?

If it's the latter, I would conclude that this is good to know, but probably fine until further evidence for major differences emerge.

**Comment by Dominik1123** [comment]
@coldfix Yes, the difference of the penalty function is small, but the difference in the resulting variables is noticeable. `grep`-ing for `^.{8}->k1` gives the following output:

```lang-none
MADX
----
gte1qd11->k1              3.61124e-02  0.00000e+00 -1.00000e+00  1.00000e+00
gte1qd12->k1              1.05591e-01  0.00000e+00 -1.00000e+00  1.00000e+00
gte2qt11->k1              8.91030e-03  0.00000e+00 -1.00000e+00  1.00000e+00
gte2qt12->k1             -1.21816e-02  0.00000e+00 -1.00000e+00  1.00000e+00
gte2qt13->k1             -2.27649e-02  0.00000e+00 -1.00000e+00  1.00000e+00
gth1qd11->k1             -1.80429e-02  0.00000e+00 -1.00000e+00  1.00000e+00
gth1qd12->k1             -2.00416e-03  0.00000e+00 -1.00000e+00  1.00000e+00
gth2qd11->k1             -1.52122e-01  0.00000e+00 -1.00000e+00  1.00000e+00
gth2qd12->k1              1.83172e-01  0.00000e+00 -1.00000e+00  1.00000e+00

CPYMAD
------
gte1qd11->k1              3.60505e-02  0.00000e+00 -1.00000e+00  1.00000e+00
gte1qd12->k1              1.05618e-01  0.00000e+00 -1.00000e+00  1.00000e+00
gte2qt11->k1              8.97790e-03  0.00000e+00 -1.00000e+00  1.00000e+00
gte2qt12->k1             -1.21705e-02  0.00000e+00 -1.00000e+00  1.00000e+00
gte2qt13->k1             -2.27853e-02  0.00000e+00 -1.00000e+00  1.00000e+00
gth1qd11->k1             -1.80740e-02  0.00000e+00 -1.00000e+00  1.00000e+00
gth1qd12->k1             -2.02475e-03  0.00000e+00 -1.00000e+00  1.00000e+00
gth2qd11->k1             -1.52095e-01  0.00000e+00 -1.00000e+00  1.00000e+00
gth2qd12->k1              1.83178e-01  0.00000e+00 -1.00000e+00  1.00000e+00
```

However, I'm not particularly concerned with it, since both results fulfill the matching constraints, and when I crosscheck the result (in terms of lattice functions) from one version with the other, they match identically. It's just that the two versions arrive at two different matching results and I wondered what would be the reasons for that. If this is due to limited floating point precision only (i.e. all the MADX-internal options / configuration are the same), I'm fine with it.

On a side note, running the above test script through the [`madx-linux64-intel`](https://madx.web.cern.ch/madx/releases/last-rel/madx-linux64-intel) version doesn't even succeed (after about 200,000 steps it converges without success), so there seem to be some larger floating point instabilities involved in the LMDIF matching process.

**Comment by coldfix** [comment]
> @coldfix Yes, the difference of the penalty function is small, but the difference in the resulting variables is noticeable.

I see.

> However, I'm not particularly concerned with it, since both results fulfill the matching constraints, and when I crosscheck the result (in terms of lattice functions) from one version with the other, they match identically. It's just that the two versions arrive at two different matching results and I wondered what would be the reasons for that. If this is due to limited floating point precision only (i.e. all the MADX-internal options / configuration are the same), I'm fine with it.

Okay. Some differences in optimization results are to be expected due to compilation/runtime differences, as long as both versions provide a useful/consistent result.


> 
> On a side note, running the above test script through the [`madx-linux64-intel`](https://madx.web.cern.ch/madx/releases/last-rel/madx-linux64-intel) version doesn't even succeed (after about 200,000 steps it converges without success), so there seem to be some larger floating point instabilities involved in the LMDIF matching process.

Yes, there are major numerical differences between compilers, compiler versions, platforms, runtime libraries, and -of course- architectures. In particular, I've done 32-bit builds for which most of the madx tests fail or even crash. You will in most cases also get different results between the official MAD-X builds for windows/linux/macos. This can also be seen from the tests inside the MAD-X testsuite which contain lots rules to allow for certain numerical differences between the individual builds (sometimes even more significant than here).
