### ISSUE TITLE
Msys2 UCRT64 toolchain

### ISSUE THREAD

**Issue by carlkl** [hibtc/cpymad#81]
Msys2 provides now an 64bit toolchain targettting the UCRT runtimes.

This could be an alternative to the outdated msys2 m2w64-toolchain.

```
pacman -S mingw-w64-ucrt-x86_64-gcc
pacman -S mingw-w64-ucrt-x86_64-gcc-fortran
```

**Comment by coldfix** [comment]
This is great news, thanks! :)

The current windows build setup is rather hackish, using conda's [`m2w64-toolchain`](https://anaconda.org/msys2/m2w64-toolchain) package and manual compilation/linking commands (not through setuptools), likely linking against DLLs that are not the official ones for the individual python versions.

**Comment by coldfix** [comment]
@carlkl The branch [msys2-ucrt64](https://github.com/hibtc/cpymad/tree/msys2-ucrt64) has the updated build recipe. [Tests](https://github.com/hibtc/cpymad/actions/runs/758403575) are passing. It would be great if you could take a look at some of the wheels if everything is in order (can be downloaded from [here](https://github.com/hibtc/cpymad/suites/2518662391/artifacts/54535730)).

**Comment by carlkl** [comment]
Seems all OK at a first glance (win10, py-3.9) - congratulations.
I propose to leave out py-3.5 and py-3.6; these are meaningless today IMHO.

**Comment by coldfix** [comment]
Great, thanks! I think I will add a deprecation warning for py3.5, and for 3.6 as soon as it reaches EOL.
