### ISSUE TITLE
Pickle Data truncated

### ISSUE THREAD

**Issue by JoschD** [hibtc/cpymad#87]
I'm not sure where exactly this bug should be attacked, but if I try to receive large data from the cpymad madx instance (e.g. a twiss-dataframe) I am getting an error 
`_pickle.UnpicklingError: pickle data was truncated`
(minrpc/connection.py:l47)

This seems to be Linux-Kernel specific and may or may not have to do with WSL.
Kernel that works flawlessly: `5.4.72-microsoft-standard-WSL2`
Kernel that throws error: `5.10.16.3-microsoft-standard-WSL2`

Maybe this info helps someone getting stuck with the same problem. 
I tried to fix it by setting different buffer-sizes, but it stopped communicating then completely.

I do not have a "pure" linux with the `5.10`-Kernel available, maybe someone can test this?

**Comment by ydutheil** [comment]
Hi,
can you check on the version  of minrpc, and cpymad, that you are using ?

**Comment by JoschD** [comment]
Hey,
thank you very much for the quick reply: 
```
minrpc==0.0.11
cpymad==1.8.1
```

**Comment by ydutheil** [comment]
Can you upgrade minrpc and tell me if that solves the issue ? I think I remember that issue and wanting to bump the requirement in the cpymad setup file, but haven't done it so far.

**Comment by JoschD** [comment]
Hey, 
Thank you very much for your help. Seems I am worse at googeling errors than I thought ;)
With minrpc version `0.1.0` it runs smoothly on my `5.10`-Kernel!
